apiVersion: v2
name: todolist-app
description: A Helm chart for the TodoList Flask application with PostgreSQL, following Kubernetes best practices.
type: application
version: 1.0.0
appVersion: "2.0.0"
dependencies: []
keywords:
  - flask
  - todolist
  - postgresql
  - api
maintainers:
  - name: Nikolas Schaffer
    email: nikolatsdev@users.noreply.github.com
sources:
  - https://github.com/nikolastsdev/platform-engineer
