# ==============================================================================
# Kind Cluster Configuration
# - 1 control-plane + 3 workers
# - Portas expostas no host para acesso direto (sem port-forward)
# ==============================================================================
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: todolist-platform

nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 5000
        hostPort: 5000
        listenAddress: 0.0.0.0
        protocol: TCP
      - containerPort: 8080
        hostPort: 8080
        listenAddress: 0.0.0.0
        protocol: TCP
  - role: worker
  - role: worker
  - role: worker
