apiVersion: v1
kind: ConfigMap
metadata:
  name: todolist-config
  namespace: todolist
data:
  APP_NAME: "TodoList Platform"
  APP_COLOR: "blue"
  APP_PORT: "5000"
  DB_HOST: "postgresql.todolist-db.svc.cluster.local"
  DB_PORT: "5432"
  DB_NAME: "todolist"
