apiVersion: v1
kind: Service
metadata:
  name: todolist
  namespace: todolist
  labels:
    app.kubernetes.io/name: todolist
    app.kubernetes.io/component: api
spec:
  type: NodePort
  ports:
    - name: http
      port: 5000
      targetPort: 5000
      nodePort: 30000
      protocol: TCP
  selector:
    app.kubernetes.io/name: todolist
