{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "todolist-app.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "todolist-app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  {{- if .Values.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if .Values.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "todolist-app.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
