apiVersion: v1
kind: Secret
metadata:
  name: {{ include "todolist-app.fullname" . }}-secrets
  labels:
    {{- include "todolist-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_USER: {{ .Values.secrets.dbUser | quote }}
  DB_PASSWORD: {{ .Values.secrets.dbPassword | quote }}
  SESSION_KEY: {{ .Values.secrets.sessionKey | quote }}
  ADMIN_USER: {{ .Values.secrets.adminUser | quote }}
  ADMIN_PASSWORD: {{ .Values.secrets.adminPassword | quote }}
  CLEANUP_TOKEN: {{ .Values.secrets.cleanupToken | quote }}
